### ISSUE TITLE
10 sided dice report incorrect "label"

### ISSUE THREAD

**Issue by tim-duncan** [3d-dice/dice-box-threejs#2]
While playing around I noticed that all the 10 sided dice (d10, d100) report the "label" value as off by 1.

In the example below, the d10 rolls 8 and the object returned by DiceBox.roll() has the correct 'value' but for some reason the 'label' is set to "9".
![image](https://user-images.githubusercontent.com/1584842/194685972-b7ca85b9-241e-4f6d-909d-1d6202ccdb14.png)

```
{
    "notation": "d10",
    "sets": [
        {
            "num": 1,
            "type": "d10",
            "sides": 10,
            "rolls": [
                {
                    "type": "d10",
                    "sides": 10,
                    "id": 0,
                    "value": 8,
                    "label": "9",
                    "reason": "natural"
                }
            ],
            "total": 8
        }
    ],
    "modifier": 0,
    "total": 8
}
```

I looked at the code where it sets the label but I couldn't figure out why its doesn't use the same index into the value and label arrays around line 103 in DiceFactory.js:
```
	if (['d10','d2'].includes(this.shape)) matindex += 1;

	let value = diceobj.values[((matindex-1) % diceobj.values.length)];
	let label = diceobj.labels[(((matindex-1) % (diceobj.labels.length-2))+2)];
```

**Comment by lucasishuman** [comment]
Seeing some issues with d10s too.

Like here you can see I specified `2d10@8,1` in my notation, but the values are `5, 1` and labels are `6, 2`

![image](https://user-images.githubusercontent.com/1753761/197865389-f4b21239-5b7b-435f-9cb7-f3a6e043bfbc.png)

Other size dice seem ok so far. Except d100, but I'm not sure if that is currently supported...

![image](https://user-images.githubusercontent.com/1753761/197865930-3fd1b17c-ac2e-4dab-8c5f-e896908958c0.png)

This is such a great library - thanks!

**Comment by CapsE** [comment]
I was about to write that I can't reproduce the error yesterday but now I'm seeing it too. D10 are all over the place. Looks almost like the @ notation doesn't work for them. The Code-Sandbox example works perfectly fine though... I tried to recreate it as close as possible and still can't get it to work.
I'm looking at your source code right now. I'll let you know if I find something.

**Comment by frankieali** [comment]
This is the problem:
https://github.com/3d-dice/dice-box-threejs/blob/2b429ff8d1a38392a7156abf774f665c416c5560/src/DiceFactory.js#L103-L106

Making a fix now

**Comment by frankieali** [comment]
Here it is. I'll bump the NPM release as well. Thanks for catching this issue.
https://github.com/3d-dice/dice-box-threejs/blob/38c5ef16eefe9be443417066ff60da5ded48f8b5/src/DiceFactory.js#L94-L111

**Comment by frankieali** [comment]
NPM package updated to `0.0.9`

**Comment by frankieali** [comment]
Yup, you're right. I'm seeing the issue as well. I was focused on fixing the labels. I didn't see that deterministic rolls for d10's was broken.

**Comment by frankieali** [comment]
Ok, the add method still had a bug. Fixed again. Fingers crossed this is the last thing.
Release version `0.0.12`

**Comment by CapsE** [comment]
Works like a charm! Thanks!
