### ISSUE TITLE
What is notation format for multiple deterministic die types and values?

### ISSUE THREAD

**Issue by lucasishuman** [3d-dice/dice-box-threejs#3]
In the README it shows that you can specify the results for a given roll like ~

```js
// rolls six dice that will land on 4's
const notation = '6d6@4,4,4,4,4,4';
Box.roll(notation)
```

How can one specify multiple values for multiple dice types? I don't see anything in the docs like this, so maybe it's not currently supported?

I'm looking for something like...

```js
// rolls 2d4 with values of 1, 3 and 2d6 with values of 4, 4 and 1d20 with value of 14
const notation = '2d4@1,3&2d6@4,4&1d20@14';
Box.roll(notation)
```

Thanks!

**Comment by frankieali** [comment]
You can do `3d6+3d10@3,3,3,8,8,8`. The deterministic values are assigned in the order they're processed from left to right. If a value is not assigned then the die will roll as normal.

`Box.roll(['2d4@1','3&2d6@4','4&1d20@14'])` would be nice to have but I did not set up the dice parser in this project.

**Comment by lucasishuman** [comment]
Excellent - thank you for the info.
