### ISSUE TITLE
Hi. Is it possible to add your own cube texture?

### ISSUE THREAD

**Issue by nickgipp** [3d-dice/dice-box-threejs#5]
Hi. Is it possible to add your own cube texture?

**Comment by frankieali** [comment]
Yes it is possible to use your own texture. You might be able to figure it out from this demo https://codesandbox.io/s/dice-box-threejs-j79h35.
However, in this project, the textures are just background elements and the numbers are rendered individually over top. If you're looking to replace the numbers with symbols then that's a little more complicated. You'd have to create a custom font with the symbols you want. I'd have to dig into the code to see how to support a custom theme, but it is possible. The original project that I based this one on, [Major's 3D Dice](https://majorvictory.github.io/3DDiceRoller/), did the same for star wars dice.

**Comment by nickgipp** [comment]
Thanks. I managed to replace the texture by replacing the picture of another theme leaving the name the same
